version: "3.5"

services:
  postgres:
    image: postgres:15-alpine
    network_mode: host
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}

volumes:
  postgres:
