# Generated by Django 4.1.3 on 2022-11-21 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_alter_image_parent_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='path',
            new_name='uri',
        ),
    ]
