# Generated by Django 4.1.3 on 2022-11-23 10:03

from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_rename_path_link_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='expiring_link_duration_seconds',
            field=models.PositiveIntegerField(null=True, validators=[image.models.validate_expiring_link_duration_seconds]),
        ),
    ]
