# Generated by Django 4.1.3 on 2022-11-20 23:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('link', models.BooleanField()),
                ('expiry_link', models.BooleanField()),
                ('expiry_link_seconds',
                 models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)])),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(error_messages={'unique': 'Plan with that name already exists.'}, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanToImageSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_specifications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.imagespecifications')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.plan')),
            ],
            options={
                'unique_together': {('image_specifications', 'plan')},
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='includes',
            field=models.ManyToManyField(through='plan.PlanToImageSpecifications', to='plan.imagespecifications'),
        ),
    ]
