# Generated by Django 4.1.3 on 2022-11-21 04:10

from django.db import migrations


def create_basic_plan_types(apps, schema_editor):
    specs = apps.get_model('plan', 'ImageSpecifications')
    basic_spec = specs.objects.create(
        width=200, height=200, link=True, expiry_link=False
    )
    basic_spec.save()

    premium_spec = specs.objects.create(
        width=400, height=400, link=True, expiry_link=False)
    premium_spec.save()

    enterprise_spec = specs.objects.create(
        width=0, height=0, link=True, expiry_link=True)
    enterprise_spec.save()

    plan = apps.get_model('plan', 'Plan')
    basic_plan = plan.objects.create(name="Basic")
    basic_plan.includes.add(basic_spec)
    basic_plan.save()

    premium_plan = plan.objects.create(name="Premium")
    premium_plan.includes.add(basic_spec)
    premium_plan.includes.add(premium_spec)
    premium_plan.save()

    ent_plan = plan.objects.create(name="Enterprise")
    ent_plan.includes.add(basic_spec)
    ent_plan.includes.add(premium_spec)
    ent_plan.includes.add(enterprise_spec)
    ent_plan.save()


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_basic_plan_types)
    ]
